# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30819cb3956429bfa02e744e9d24d35324e1cdf4a3e20c88a01dd7fb67a3e015bfb92327e90ff3666cd8af456c2c34e986a14950d84200fceef804a76aa01ce6

test:
  secret_key_base: 80dedf515e6f690f6ff4c5ff3374412e06ba680b29830ce6dc4936ae0137ea5736a083229fbba696f2cb06cb0a9b9f291b29c17241edd3f3121fdb4d4d5bdccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
